# Generated by Django 4.0.5 on 2022-06-24 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_rename_decisions_game_played_lose_decisions_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game_Played',
        ),
    ]
