# Generated by Django 4.0.5 on 2022-06-24 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0003_delete_game_played'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game_Played',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.CharField(max_length=24)),
                ('win_decisions', models.CharField(max_length=12)),
                ('lose_decisions', models.CharField(max_length=12)),
            ],
        ),
    ]
